/** The PromptEye API client. Depends on `zod` alone and knows nothing about MCP. */
export { PromptEyeApi, DEFAULT_TIMEOUT_MS, type PromptEyeApiOptions } from "./client.js";
export { API_ERROR_MESSAGES, PromptEyeApiError, type ApiErrorDetail } from "./errors.js";
export type { FetchLike, Query, RequestOptions } from "./http.js";
export type {
  AccountResource,
  AiTrafficParams,
  AiTrafficRankingParams,
  CategoriesResource,
  CompetitorsResource,
  ContentBriefsResource,
  DateRange,
  GoogleResource,
  IntegrationsResource,
  KnowledgeBaseResource,
  Pagination,
  ProjectsResource,
  PromptGroupsResource,
  PromptsResource,
  PromptSuggestionsResource,
  RankingParams,
  SearchRankingParams,
  SourcesResource,
  TrafficCountParams,
  TrafficCrawlParams,
  TrafficEventParams,
  TrafficFilters,
  TrafficResource,
  TrafficSitemapParams,
} from "./resources.js";
export {
  AccountSchema,
  AnalyticsPageSchema,
  AnalyticsSourceSchema,
  AnalyticsSummarySchema,
  CategorySchema,
  CitedDomainSchema,
  CompetitorSchema,
  ContentBriefOutlineItemSchema,
  ContentBriefPhraseSchema,
  ContentBriefSchema,
  ContentBriefSeparateArticleSchema,
  COUNTRY_CODES,
  GoogleStatusSchema,
  IntegrationSchema,
  IntegrationsStatusSchema,
  KnowledgeBaseSchema,
  NewPromptSchema,
  ProjectSchema,
  PromptDetailSchema,
  PromptGroupSchema,
  PromptSchema,
  PromptSuggestionSchema,
  REPORT_REACH,
  ReportDetailSchema,
  ReportSchema,
  SearchPageSchema,
  SearchQuerySchema,
  SearchSummarySchema,
  TRAFFIC_CATEGORIES,
  TRAFFIC_GROUPS,
  TRAFFIC_KINDS,
  TrafficCountSchema,
  TrafficCrawlSchema,
  TrafficEventSchema,
  TrafficSitemapPageSchema,
  type Account,
  type AnalyticsPage,
  type AnalyticsSource,
  type AnalyticsSummary,
  type Category,
  type CitedDomain,
  type Competitor,
  type ContentBrief,
  type ContentBriefOutlineItem,
  type ContentBriefPhrase,
  type ContentBriefSeparateArticle,
  type CountryCode,
  type CreateContentBriefInput,
  type CreateProjectInput,
  type GoogleStatus,
  type GoogleSync,
  type Integration,
  type IntegrationsStatus,
  type KnowledgeBase,
  type List,
  type Metrics,
  type MetricsChange,
  type ModelMetrics,
  type NewPrompt,
  type Page,
  type Project,
  type Prompt,
  type PromptDetail,
  type PromptGroup,
  type PromptInput,
  type PromptSuggestion,
  type SearchPage,
  type SearchQuery,
  type SearchSummary,
  type TrafficCategory,
  type TrafficCount,
  type TrafficCountPage,
  type TrafficCrawl,
  type TrafficEvent,
  type TrafficGroup,
  type TrafficKind,
  type TrafficSitemapPage,
  type TrafficSitemapState,
  type TrafficSitemapUrl,
  type CreateReportInput,
  type Report,
  type ReportDetail,
  type ReportReach,
} from "./schemas.js";
