import { z } from "zod";
import { MetricsSchema, ModelSchema, NullableChangeSchema } from "./common.js";

/*
 * The models the PromptEye API already serves live in the API client, which is
 * the single source of truth for them. The rest are mirrored here until the
 * API grows the endpoints, and are answered from sample data meanwhile.
 */
export {
  AccountSchema,
  AcceptedPromptSuggestionSchema,
  AnalyticsPageSchema,
  AnalyticsSourceSchema,
  AnalyticsSummarySchema,
  AUDIT_STATUSES,
  AUDIT_URL_STATUSES,
  AuditAnalysisSchema,
  AuditSchema,
  AuditStatusSchema,
  AuditUrlResultSchema,
  AuditUrlStatusSchema,
  AuditUsageSchema,
  BRAND_ANALYSIS_AVAILABILITY_REASONS,
  BRAND_ANALYSIS_RUN_STATUSES,
  BrandAnalysisAvailabilityReasonSchema,
  BrandAnalysisAvailabilitySchema,
  BrandAnalysisGapSchema,
  BrandAnalysisRankingEvidenceSchema,
  BrandAnalysisRunSchema,
  BrandAnalysisRunStatusSchema,
  BrandAnalysisSentimentSchema,
  CategorySchema,
  CitedDomainSchema,
  CitedPageSchema,
  CompanyProfileSchema,
  CompetitorExclusionListSchema,
  CompetitorExclusionSchema,
  CompetitorSchema,
  ContentBriefSchema,
  COUNTRY_CODES,
  GoogleStatusSchema,
  KnowledgeBaseSchema,
  NewPromptSchema,
  ProjectSchema,
  PromptDetailSchema,
  PromptGroupSchema,
  PromptGroupSettingsSchema,
  PromptSchema,
  PromptSettingsSchema,
  PromptSuggestionSchema,
  SUGGESTION_RUN_SKIP_REASONS,
  SUGGESTION_RUN_AVAILABILITY_REASONS,
  SuggestionRunSchema,
  SuggestionRunSkipReasonSchema,
  SuggestionRunAvailabilityReasonSchema,
  SuggestionRunAvailabilitySchema,
  REPORT_REACH,
  ReplaceCompetitorExclusionsRequestSchema,
  ReportDetailSchema,
  ReportSchema,
  SearchPageSchema,
  SearchQuerySchema,
  SearchSummarySchema,
  CRAWL_HEALTH_ASSESSMENT_KEYS,
  CRAWL_HEALTH_LEVELS,
  TOPICAL_MAP_CLUSTER_INTENTS,
  TOPICAL_MAP_STATUSES,
  TopicalMapClusterIntentSchema,
  TopicalMapClusterSchema,
  TopicalMapListSchema,
  TopicalMapPillarSchema,
  TopicalMapSchema,
  TopicalMapStatusSchema,
  TopicalMapSummarySchema,
  TRAFFIC_GROUPS,
  CrawlHealthAssessmentKeySchema,
  CrawlHealthLevelSchema,
  TrafficCategorySchema,
  TrafficCountSchema,
  TrafficCrawlHealthAssessmentSchema,
  TrafficCrawlHealthSchema,
  TrafficCrawlIssueSchema,
  TrafficCrawlSchema,
  TrafficEventSchema,
  TrafficGroupSchema,
  TrafficKindSchema,
  TrafficSitemapPageSchema,
  TrafficSitemapStateSchema,
  TrafficSitemapUrlSchema,
  UpdateKnowledgeBaseRequestSchema,
  UpdateProjectRequestSchema,
  UpdatePromptRequestSchema,
  type Account,
  type AcceptedPromptSuggestion,
  type AcceptPromptSuggestionInput,
  type AnalyticsPage,
  type AnalyticsSource,
  type AnalyticsSummary,
  type Audit,
  type AuditAnalysis,
  type AuditStatus,
  type AuditUrlResult,
  type AuditUrlStatus,
  type AuditUsage,
  type AuditUsageQuery,
  type BrandAnalysisAvailability,
  type BrandAnalysisAvailabilityReason,
  type BrandAnalysisGap,
  type BrandAnalysisRankingEvidence,
  type BrandAnalysisRun,
  type BrandAnalysisRunStatus,
  type BrandAnalysisSentiment,
  type Category,
  type CitedDomain,
  type CitedPage,
  type CompanyProfile,
  type Competitor,
  type CompetitorExclusion,
  type ContentBrief,
  type CreateAuditInput,
  type CreateCategoryInput,
  type CreateContentBriefInput,
  type CreatePromptGroupInput,
  type CreateProjectInput,
  type CreateTopicalMapInput,
  type GoogleStatus,
  type GoogleSync,
  type KnowledgeBase,
  type List,
  type NewPrompt,
  type Project,
  type Prompt,
  type PromptDetail,
  type PromptGroup,
  type PromptGroupSettings,
  type PromptInput,
  type PromptSettings,
  type PromptSuggestion,
  type SuggestionRun,
  type SuggestionRunSkipReason,
  type SuggestionRunAvailability,
  type SuggestionRunAvailabilityReason,
  type RegenerateTopicalMapClusterInput,
  type SearchPage,
  type SearchQuery,
  type SearchSummary,
  type CrawlHealthAssessmentKey,
  type CrawlHealthLevel,
  type TopicalMap,
  type TopicalMapClusterIntent,
  type TopicalMapSummary,
  type TrafficCategory,
  type TrafficCount,
  type TrafficCountPage,
  type TrafficCrawl,
  type TrafficCrawlHealth,
  type TrafficCrawlHealthAssessment,
  type TrafficCrawlIssue,
  type TrafficEvent,
  type TrafficGroup,
  type TrafficKind,
  type TrafficSitemapPage,
  type TrafficSitemapState,
  type TrafficSitemapUrl,
  type CreateReportInput,
  type Report,
  type ReportDetail,
  type ReportReach,
  type ReplaceCompetitorExclusionItem,
  type ReplaceCompetitorExclusionsInput,
  type UpdateKnowledgeBaseInput,
  type UpdatePromptGroupInput,
  type UpdateProjectInput,
  type UpdatePromptInput,
} from "../api/schemas.js";

export const BREAKDOWN_KEYS = ["day", "model", "prompt"] as const;
export const BreakdownSchema = z.enum(BREAKDOWN_KEYS);

export const BreakdownEntrySchema = z.object({
  key: z.string(),
  label: z.string(),
  metrics: MetricsSchema,
});

export const VisibilitySummarySchema = z.object({
  startDate: z.string(),
  endDate: z.string(),
  models: z.array(ModelSchema),
  totals: MetricsSchema,
  change: NullableChangeSchema,
  aiTrafficTotal: z.number().nullable(),
  breakdown: z.array(BreakdownEntrySchema),
  breakdownTruncated: z.boolean(),
});

export const VisibilityRowSchema = z.object({
  date: z.string(),
  promptId: z.string(),
  prompt: z.string(),
  model: ModelSchema,
  answered: z.boolean().nullable(),
  visibility: z.number(),
  position: z.number().nullable(),
});

export const SourceSchema = z.object({
  url: z.string(),
  domain: z.string(),
  title: z.string().nullable(),
});

export const AnswerSchema = z.object({
  id: z.string(),
  date: z.string(),
  promptId: z.string(),
  prompt: z.string(),
  model: ModelSchema,
  brand: z.enum(["named", "missing"]),
  position: z.number().nullable(),
  text: z.string(),
  sources: z.array(SourceSchema),
});

const DistributionEntrySchema = z.object({
  key: z.string(),
  count: z.number(),
  percentage: z.number(),
});

export const CitationQualitySchema = z.object({
  analysedOn: z.string(),
  role: z.object({
    totalResponses: z.number(),
    mentionedResponses: z.number(),
    distribution: z.array(DistributionEntrySchema),
  }),
  sentiment: z.object({
    totalResponses: z.number(),
    mentionedResponses: z.number(),
    distribution: z.array(DistributionEntrySchema),
  }),
});

export type Breakdown = z.infer<typeof BreakdownSchema>;
export type VisibilitySummary = z.infer<typeof VisibilitySummarySchema>;
export type VisibilityRow = z.infer<typeof VisibilityRowSchema>;
export type Answer = z.infer<typeof AnswerSchema>;
export type CitationQuality = z.infer<typeof CitationQualitySchema>;

/** Whether an answer named the brand. */
export type BrandPresence = z.infer<typeof AnswerSchema>["brand"];
