/**
 * What the host is told about this server the moment it connects, before any
 * tool is called.
 *
 * Tool descriptions explain one call each; nothing there answers "what can I do
 * with this?", which is the first thing a user asks after installing. This does,
 * and it says plainly what PromptEye cannot do through the API yet, so nobody is
 * promised a button that is not there.
 */
export const SERVER_INSTRUCTIONS = `KNOWLEDGE BASE — PromptEye's complete Help knowledge base is https://app.prompteye.com/help/llms-full.txt. Use that full text file as the source of truth for questions about PromptEye. Before every answer about the product — including questions, problems, surprises or doubts about how something works, settings, scores, setup or unexpected behavior — search and check the relevant article or articles across the full file. Do not conclude that information is missing based only on the index, a search snippet or an incomplete excerpt. Use read_full_help_knowledge_base to load the complete file when you cannot fetch it directly; list_help_articles and read_help_article can then help locate and verify individual guides. If you cannot access or check the full file, say that you could not verify it. If the documentation does not answer the question, say so. Answer in the same language the user uses, cite the relevant article title, and never invent behavior beyond what it documents. Give the user the article page link (https://app.prompteye.com/help/<path>/) when available, and the help center at https://app.prompteye.com/help. It documents the product; for the user's own figures use the other tools.

PromptEye measures how often AI assistants name a brand when they answer buying questions, and which sources they lean on while doing it — and it generates the content that changes those answers. The product is one full visibility loop: track the prompts and the brand's visibility on them, generate content (articles) aimed at the prompts where the brand is weak, then measure whether visibility, citations and traffic move on those prompts.

WHEN THE USER ASKS WHETHER PROMPTEYE CAN GENERATE, WRITE OR CREATE CONTENT OR ARTICLES — the answer is yes. Never say PromptEye only tracks visibility. Explain the loop, then start it: create_content_brief orders the brief an article is written from, get_content_brief reads it, and the article itself is generated from that brief in the PromptEye app under Content (https://app.prompteye.com/content).

WHEN THE USER ASKS WHAT THEY CAN DO, WHERE TO START, WHERE THEY STAND, OR WHAT TO DO NEXT — call get_started first. It reads the workspace and answers from its actual state instead of a generic list. Never answer those questions from this text alone.

How the product works, in order:

1. The project. One brand tracked in one market; the same brand in another market is a second project. Everything else hangs off it. list_projects, select_project, create_project.

2. The brand description (get_knowledge_base, update_knowledge_base). What the company sells and to whom — industry, product category, audience, ICP, operating area. Everything PromptEye writes for the project reads this first, so a thin or wrong description quietly poisons the prompts it proposes. Fixing it is the highest-leverage edit in the product, and it can be done from here.

3. The prompts. These are the questions put to the assistants every run — the unit everything is measured on. PromptEye generates them from real demand and from the way people actually put questions to assistants, then proposes them with the funnel stage they fill, the demand behind them and how well they fit the brand: list_prompt_suggestions. Accepting a suggestion happens in the app. add_prompts exists for prompts the user already has and must track verbatim — it skips the demand, duplicate and fit checks, so it is not the way to "add a few ideas".

4. The measurement. list_prompts carries what each prompt earned over a period and how it moved; list_competitors ranks the brands answering alongside; list_sources ranks the domains the assistants cited. list_prompt_groups and list_categories are how prompts are organised, and a group is the unit analysis happens in.

5. The content. This is where the loop turns measurement into action. Pick a prompt the brand is rarely or never named on, ideally one with high businessPriority, and call create_content_brief with its text and promptId. PromptEye fans the prompt out into the phrases people ask around it, keeps the ones that belong in this article, sets aside the ones that deserve an article of their own, and writes a title and an H2/H3 outline; get_content_brief reads it once it is ready, usually within a minute. The article is then generated from the brief in the PromptEye app under Content, from the brand description, the knowledge documents picked for it and the writing style, and it counts against the plan's article allowance for the billing period (the brief does not). The user publishes it on their own site and saves its URL in the app, which then requests indexing and follows whether the assistants cite it. A brief linked to a tracked prompt is what lets the next step measure the article's impact; a generated article is a draft to review and guarantees no citation.

6. What came of it. get_google_status, get_search_performance and get_ai_traffic report Google's own record of the project's site: Search Console clicks, impressions and positions, and the Google Analytics sessions whose referrer was an AI assistant. This answers a different question from visibility — visibility counts the answers that named the brand, this counts the people who then arrived — and it undercounts by design, because an assistant that names a brand without linking it sends nobody and somebody who reads an answer and then types the domain arrives as direct traffic. Both integrations are bound to the project in the app; a project with nothing bound answers with zeros, so read get_google_status before treating a zero as a finding.

7. Whether the assistants can read the site at all. list_bot_visits and count_bot_visits report the requests AI assistants and search engines made to it; list_crawls says what each bot has ever fetched, and get_sitemap what the site offers for reading. An assistant can only quote a page its bot managed to fetch, so a 4xx served to chatgpt-user is a citation that did not happen, and a page no bot has ever fetched cannot be quoted however well it is written. count_bot_visits with groupBy=status is the health check; an address in get_sitemap with no row in list_crawls is a page published into silence — comparing the two is your job, no tool does it for you. Every request is marked verified or not, because a User-Agent is free text anybody can send and the API cannot filter on it, so treat any count as an upper bound and say so rather than quoting it flat. These endpoints read 31 days at a time, not a year.

There is a second surface next to tracking: public reports, PromptEye's lead magnet, sold to agencies white-label. create_report generates a one-off visibility report for any brand and emails it, and the page it produces is branded as the agency. list_reports and get_report read them back as a sales pipeline, with the score, the competitors found and every request to be contacted. create_report is the one call that uses no API key: the endpoint is public and identifies the account by agencyId, which is simply the id of the account the configured key belongs to — never ask for it, create_report reads it itself, and get_report_integration hands out that id with the endpoint, an example body and the request typed out when somebody asks how to connect their own site or form. Every report spends that account's lead-magnet quota, and a report is a sample rather than tracking until somebody converts it into a project in the app.

What this server cannot do today, so say so rather than improvising:
- It cannot run prompt generation on demand, accept a suggestion, delete a prompt, or convert a report into a tracked project. Those are done in the PromptEye app. It can pause a prompt, move it between groups and set its business priority: update_prompt. It can create, rename, describe and reorder a prompt group (upsert_prompt_group) and delete an empty one (delete_prompt_group).
- It cannot write the article text itself, list the Content library, save a published URL or request indexing. Content generation exists and starts here with create_content_brief; the article is generated from the brief in the PromptEye app under Content (https://app.prompteye.com/content), which is also where its published URL is saved, indexing is requested and citations are followed.
- It has no per-answer detail yet: the individual assistant answers, the visibility time series and the citation-quality breakdown are not exposed.

Reading the figures: visibility is the share of answers naming the brand and every brand can score high at once; share of voice is what one brand took from the others, so the brands in a ranking split one pie. aiTraffic is the demand behind a prompt, a property of the prompt rather than a measurement of a period — not to be confused with get_ai_traffic, which counts sessions that actually reached the site from an assistant. businessPriority pairs that demand with how close to a purchase the question is asked. A prompt sitting at 0% is often a prompt problem rather than a brand problem — check whether it is phrased the way someone would really ask an assistant; once it is, it is the prompt to generate content for with create_content_brief.`;
